"""altered network status

Revision ID: 8518b6dbb28b
Revises: 8c20cd07973a
Create Date: 2023-12-07 23:30:13.567655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8518b6dbb28b'
down_revision: Union[str, None] = '8c20cd07973a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("NetworkInfo", "Network_Status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column("NetworkInfo", sa.Column("Network_Status", sa.String(length=255),nullable=True))
    # ### end Alembic commands ###
