"""modified computer info

Revision ID: 8c20cd07973a
Revises: 70126ec33944
Create Date: 2023-12-06 03:00:35.607647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c20cd07973a'
down_revision: Union[str, None] = '70126ec33944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column("ComputerInfo", "Computer_Status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ComputerInfo", sa.Column("Computer_Status", sa.String(length=255), nullable=True))
  
    # ### end Alembic commands ###
