"""Added added all tables

Revision ID: d95c7e2ce1d8
Revises: 30dfe0d8f93d
Create Date: 2023-11-20 23:44:05.013794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95c7e2ce1d8'
down_revision: Union[str, None] = '30dfe0d8f93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
